export const APP_PREFIX = `cflui.`;
export const FIND_PATIENT_APP = APP_PREFIX + 'findPatient';
export const FIND_CAREGIVER_APP = APP_PREFIX + 'findCaregiver';
export const REGISTER_PATIENT_APP = APP_PREFIX + 'registerPatient';
export const REGISTER_CAREGIVER_APP = APP_PREFIX + 'registerCaregiver';
export const VMP_CONFIG_APP = APP_PREFIX + 'vmpConfig';
export const VMP_VACCINATION_SCHEDULE_APP = APP_PREFIX + 'vmpVaccinationSchedule';
export const VMP_ADDRESS_DATA_APP = APP_PREFIX + 'vmpAddressData';
export const VMP_TRANSLATIONS_APP = APP_PREFIX + 'vmpTranslations';
